# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [25]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
#%pip install --upgrade selenium
#%pip install webdriver-manager

#### Passo 2: Importar bibliotecas

In [26]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys

#### Passo 3: Criar navegador

In [27]:
driver = webdriver.Chrome()

#### Passo 4: Acessar site

In [28]:
# url: 'https://pubmed.ncbi.nlm.nih.gov/

driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### Passo 5: Fechar navegador

In [29]:
driver.quit()

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [30]:
driver = webdriver.Chrome() 
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### 6.2: Selecionar o campo de busca pelo id

In [31]:
campo_busca = driver.find_element(By.ID, "id_term")

#### 6.3: Escrever um texto no campo de busca

In [32]:
campo_busca = driver.find_element(By.ID, "id_term")
campo_busca.send_keys("Pokemon")

#### 6.4: Clicar no Botão Pesquisar

In [33]:
driver.find_element(By.CLASS_NAME, "search-btn").click()

#### 6.5: Fechar navegador

In [34]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [35]:
driver = webdriver.Chrome() 
driver.get('https://pubmed.ncbi.nlm.nih.gov/')
campo_busca = driver.find_element(By.ID, "id_term")
campo_busca.send_keys("Pokemon",Keys.ENTER)
resultados = driver.find_elements(By.CLASS_NAME, "docsum-content")
print("Total resultados encontrados: ", len(resultados))

Total resultados encontrados:  10

#### 7.1: Listar o título de todos os resultados

In [36]:
lista_de_titulos=[]
for i in resultados:
    titulo = i.find_element(By.CLASS_NAME, "docsum-title").text
    lista_de_titulos.append(titulo)

lista_de_titulos

['Primary Care: Its Pokemon Moment.',
 'Impact of Pokemon Go on Physical Activity: A Systematic Review and Meta-Analysis.',
 'Effects of Pokemon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review.',
 'Influence of Pokemon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review.',
 'Going Forward with Pokemon Go.',
 'Pokemon contagion.',
 'Random forests, sound symbolism and Pokemon evolution.',
 'Pokemon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians.',
 'Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms.',
 'Pokemon GO and Physical Activity in Asia: Multilevel Study.']

#### 7.2: Listar o link de todos os resultados

In [37]:
lista_de_links=[]
for j in resultados:
    lista_de_links.append(j.find_element(By.CLASS_NAME,"docsum-title").get_attribute("href"))

lista_de_links

['https://pubmed.ncbi.nlm.nih.gov/38556037/',
 'https://pubmed.ncbi.nlm.nih.gov/31836333/',
 'https://pubmed.ncbi.nlm.nih.gov/33922978/',
 'https://pubmed.ncbi.nlm.nih.gov/37955949/',
 'https://pubmed.ncbi.nlm.nih.gov/30568365/',
 'https://pubmed.ncbi.nlm.nih.gov/11811868/',
 'https://pubmed.ncbi.nlm.nih.gov/36598905/',
 'https://pubmed.ncbi.nlm.nih.gov/27479151/',
 'https://pubmed.ncbi.nlm.nih.gov/39095579/',
 'https://pubmed.ncbi.nlm.nih.gov/29907559/']

#### 7.3: Acessar um dos links

In [38]:
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

In [39]:
driver = webdriver.Chrome()
driver.get('https://pubmed.ncbi.nlm.nih.gov/38556037/')

##### 1) Título

In [40]:
titulo= driver.find_element(By.CLASS_NAME, "heading-title").text
print(titulo)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".heading-title"}
  (Session info: chrome=152.0.7977.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff77fa917f5+5855]
	chromedriver!(No symbol) [0x7ff77f9b83a0]
	chromedriver!(No symbol) [0x7ff77f7e5d7d]
	chromedriver!(No symbol) [0x7ff77f840d2e]
	chromedriver!(No symbol) [0x7ff77f84103c]
	chromedriver!(No symbol) [0x7ff77f891c67]
	chromedriver!(No symbol) [0x7ff77f88e828]
	chromedriver!(No symbol) [0x7ff77f83316b]
	chromedriver!(No symbol) [0x7ff77f8340a3]
	chromedriver!GetHandleVerifier [0x7ff77feb6c9b+42acfb]
	chromedriver!GetHandleVerifier [0x7ff77fee2422+456482]
	chromedriver!GetHandleVerifier [0x7ff77fed63ce+44a42e]
	chromedriver!GetHandleVerifier [0x7ff77fb8d87e+1018de]
	chromedriver!(No symbol) [0x7ff77f9c4e9c]
	chromedriver!(No symbol) [0x7ff77f9c0ac4]
	chromedriver!(No symbol) [0x7ff77f9c0c54]
	chromedriver!(No symbol) [0x7ff77f9ac24c]
	KERNEL32!BaseThreadInitThunk [0x7ffa7924ccb7+17]
	ntdll!RtlUserThreadStart [0x7ffa79e8ad6c+2c]

##### 2) Autores

In [ ]:
autor = driver.find_element(By.CLASS_NAME,"full-name").text
print(autor)

Bryan Becker

##### 3) Ano de publicação

In [ ]:
ano_publicacao = driver.find_element(By.CLASS_NAME,"cit").text
print(ano_publicacao)

2024 Jul;137(7):577-581.

##### 4) DOI

In [ ]:
doi = driver.find_element(By.CLASS_NAME,"doi").text
print(doi)

DOI: 10.1016/j.amjmed.2024.03.020

##### 5) Tipo de publicação

In [ ]:
tipo = driver.find_element(By.CLASS_NAME,"publication-type").text
print(tipo)

Review

##### 6) Resumo

In [ ]:
resumo = driver.find_element(By.CLASS_NAME,"abstract-content").text
print(resumo)

Primary care in the United States is undergoing bursts of evolution in response to health system stresses, changing demographics, and expansion of risk and value-based reimbursement structures. The impact of primary care remains substantive and associated with improved population health. However, the spectrum of services, the nature of the physicians involved and new ways of including the patient in her, or his own care suggests that a new definition of primary care be considered, and patient expectations be heeded and understood. Evolutionary bursts yield new traits and in primary care, they are spawning new care models with significant implications for general internal medicine, internal medicine/pediatrics trained individuals and medicine subspecialties given the focus of these models on Medicare Advantage. Ultimately, changes in reimbursement and creative incentives will be two factors among many that will solidify the next stage of primary care in the United States.

##### 7) Link de acesso (como registro de referência)

In [ ]:
link = driver.current_url
print(link)

https://pubmed.ncbi.nlm.nih.gov/38556037/

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [58]:
colunas = ["Titulo", "Autor", "Ano_Publicacao", "DOI", "Tipo", "Resumo", "Link"]

tabela = pd.DataFrame(columns=colunas)

tabela

Empty DataFrame
Columns: [Titulo, Autor, Ano_Publicacao, DOI, Tipo, Resumo, Link]
Index: []

#### 2) Obter dados dos links e armazenar na tabela

In [62]:
import time


driver = webdriver.Chrome()

for link in lista_de_links:
    driver.get(link)
    time.sleep(2)  
    try:
        titulo = driver.find_element(By.CLASS_NAME, "heading-title").text
    except:
        titulo = "NONE"
    try:
        autor = driver.find_element(By.CLASS_NAME, "full-name").text
    except:
        autor = "NONE"
    try:
        ano_publicacao = driver.find_element(By.CLASS_NAME, "cit").text
    except:
        ano_publicacao = "NONE"
    try:
        doi = driver.find_element(By.CLASS_NAME, "doi").text
    except:
        doi = "NONE"
    try:
        tipo = driver.find_element(By.CLASS_NAME, "publication-type").text     
    except:
        tipo = "NONE"    
    try:
        resumo = driver.find_element(By.CLASS_NAME, "abstract-content").text
    except:
        resumo = "NONE"
    
    tabela = pd.concat([tabela, pd.DataFrame([[titulo, autor, ano_publicacao, doi, tipo, resumo, link]], columns=colunas)], ignore_index=True)

print(tabela)

                                               Titulo  \
0                                                 N/A
1                                                 N/A
2   Effects of Pokémon GO on Physical Activity and...
3   Influence of Pokémon GO on Physical Activity a...
4                       Going Forward with Pokemon Go
5                                   Pokemon contagion
6   Random forests, sound symbolism and Pokémon ev...
7   Pokémon Go and augmented virtual reality games...
8   Pokemon inhibits Bim transcription to promote ...
9   Pokémon GO and Physical Activity in Asia: Mult...
10                   Primary Care: Its Pokemon Moment
11  Impact of Pokémon Go on Physical Activity: A S...
12  Effects of Pokémon GO on Physical Activity and...
13  Influence of Pokémon GO on Physical Activity a...
14                      Going Forward with Pokemon Go
15                                  Pokemon contagion
16  Random forests, sound symbolism and Pokémon ev...
17  Pokémon Go and augmented virtual reality games...
18  Pokemon inhibits Bim transcription to promote ...
19  Pokémon GO and Physical Activity in Asia: Mult...

                         Autor               Ano_Publicacao  \
0                          N/A                          N/A
1                          N/A                          N/A
2                 Jung Eun Lee      2021 Apr 25;10(9):1860.
3                 Haiyan Liang       2023 Nov 13:25:e49019.
4                 Yvette Chong  2018 Oct-Dec;11(4):243-246.
5                   B G Zifkin      2001 Dec;94(12):1235-6.
6   Alexander James Kilpatrick   2023 Jan 4;18(1):e0279350.
7                 Maeve Serino        2016 Oct;28(5):673-7.
8                     Yan Wang       2024 Aug 3;150(8):380.
9                     Ben D Ma      2018 Jun 15;20(6):e217.
10                Bryan Becker     2024 Jul;137(7):577-581.
11             Madina Khamzina      2020 Feb;58(2):270-282.
12                Jung Eun Lee      2021 Apr 25;10(9):1860.
13                Haiyan Liang       2023 Nov 13:25:e49019.
14                Yvette Chong  2018 Oct-Dec;11(4):243-246.
15                  B G Zifkin      2001 Dec;94(12):1235-6.
16  Alexander James Kilpatrick   2023 Jan 4;18(1):e0279350.
17                Maeve Serino        2016 Oct;28(5):673-7.
18                    Yan Wang       2024 Aug 3;150(8):380.
19                    Ben D Ma      2018 Jun 15;20(6):e217.

                                      DOI           Tipo  \
0                                     N/A            N/A
1                                     N/A            N/A
2                DOI: 10.3390/jcm10091860         Review
3                      DOI: 10.2196/49019        Review.
4            DOI: 10.4103/JETS.JETS_87_17         Review
5   DOI: 10.1097/00007611-200112000-00025        Comment
6       DOI: 10.1371/journal.pone.0279350            N/A
7       DOI: 10.1097/MOP.0000000000000409         Review
8         DOI: 10.1007/s00432-024-05904-1            N/A
9                  DOI: 10.2196/jmir.9670        Review.
10      DOI: 10.1016/j.amjmed.2024.03.020         Review
11      DOI: 10.1016/j.amepre.2019.09.005  Meta-Analysis
12               DOI: 10.3390/jcm10091860         Review
13                     DOI: 10.2196/49019        Review.
14           DOI: 10.4103/JETS.JETS_87_17         Review
15  DOI: 10.1097/00007611-200112000-00025        Comment
16      DOI: 10.1371/journal.pone.0279350        Review.
17      DOI: 10.1097/MOP.0000000000000409         Review
18        DOI: 10.1007/s00432-024-05904-1           NONE
19                 DOI: 10.2196/jmir.9670        Review.

                                               Resumo  \
0                                                 N/A
1                                                 N/A
2   Augmented reality (AR) mobile game, Pokémon GO...
3   Background: Pokémon GO, an augmented reality g...
4   Pokemon Go is an augmented reality (AR) game w...
5                                                 N/A
6   This study constructs machine learning algorit...
7   Purpose of review: The recent release of Pokém...
8   Purpose: This study aims to determine whether ...
9   Background: Physical activity has long been co...
10  Primary care in the United States is undergoin...
11  Context: Pokémon Go is a popular mobile augmen...
12  Augmented reality (AR) mobile game, Pokémon GO...
13  Background: Pokémon GO, an augmented reality g...
14  Pokemon Go is an augmented reality (AR) game w...
15                                               NONE
16  This study constructs machine learning algorit...
17  Purpose of review: The recent release of Pokém...
18  Purpose: This study aims to determine whether ...
19  Background: Physical activity has long been co...

                                         Link
0   https://pubmed.ncbi.nlm.nih.gov/38556037/
1   https://pubmed.ncbi.nlm.nih.gov/31836333/
2   https://pubmed.ncbi.nlm.nih.gov/33922978/
3   https://pubmed.ncbi.nlm.nih.gov/37955949/
4   https://pubmed.ncbi.nlm.nih.gov/30568365/
5   https://pubmed.ncbi.nlm.nih.gov/11811868/
6   https://pubmed.ncbi.nlm.nih.gov/36598905/
7   https://pubmed.ncbi.nlm.nih.gov/27479151/
8   https://pubmed.ncbi.nlm.nih.gov/39095579/
9   https://pubmed.ncbi.nlm.nih.gov/29907559/
10  https://pubmed.ncbi.nlm.nih.gov/38556037/
11  https://pubmed.ncbi.nlm.nih.gov/31836333/
12  https://pubmed.ncbi.nlm.nih.gov/33922978/
13  https://pubmed.ncbi.nlm.nih.gov/37955949/
14  https://pubmed.ncbi.nlm.nih.gov/30568365/
15  https://pubmed.ncbi.nlm.nih.gov/11811868/
16  https://pubmed.ncbi.nlm.nih.gov/36598905/
17  https://pubmed.ncbi.nlm.nih.gov/27479151/
18  https://pubmed.ncbi.nlm.nih.gov/39095579/
19  https://pubmed.ncbi.nlm.nih.gov/29907559/

for link in lista_de_links:
    driver.get(link)
    titulo = driver.find_element(By.CLASS_NAME, "heading-title").text
    autor = driver.find_element(By.CLASS_NAME, "full-name").text
    ano_publicacao = driver.find_element(By.CLASS_NAME, "cit").text
    doi = driver.find_element(By.CLASS_NAME, "doi").text
    tipo = driver.find_element(By.CLASS_NAME, "publication-type").text
    resumo = driver.find_element(By.CLASS_NAME, "abstract-content").text
    
    links_dados = [titulo, autor, ano_publicacao, doi, tipo, resumo, link]

    for i in range(len(colunas)):
        tabela.loc[len(tabela), colunas[i]] = links_dados[i]

print(tabela)

In [63]:
tabela

,Titulo,Autor,Ano_Publicacao,DOI,Tipo,Resumo,Link
0,N/A,N/A,N/A,N/A,N/A,N/A,https://pubmed.ncbi.nlm.nih.gov/38556037/
1,N/A,N/A,N/A,N/A,N/A,N/A,https://pubmed.ncbi.nlm.nih.gov/31836333/
2,Effects of Pokémon GO on Physical Activity and...,Jung Eun Lee,2021 Apr 25;10(9):1860.,DOI: 10.3390/jcm10091860,Review,"Augmented reality (AR) mobile game, Pokémon GO...",https://pubmed.ncbi.nlm.nih.gov/33922978/
3,Influence of Pokémon GO on Physical Activity a...,Haiyan Liang,2023 Nov 13:25:e49019.,DOI: 10.2196/49019,Review.,"Background: Pokémon GO, an augmented reality g...",https://pubmed.ncbi.nlm.nih.gov/37955949/
4,Going Forward with Pokemon Go,Yvette Chong,2018 Oct-Dec;11(4):243-246.,DOI: 10.4103/JETS.JETS_87_17,Review,Pokemon Go is an augmented reality (AR) game w...,https://pubmed.ncbi.nlm.nih.gov/30568365/
5,Pokemon contagion,B G Zifkin,2001 Dec;94(12):1235-6.,DOI: 10.1097/00007611-200112000-00025,Comment,N/A,https://pubmed.ncbi.nlm.nih.gov/11811868/
6,"Random forests, sound symbolism and Pokémon ev...",Alexander James Kilpatrick,2023 Jan 4;18(1):e0279350.,DOI: 10.1371/journal.pone.0279350,N/A,This study constructs machine learning algorit...,https://pubmed.ncbi.nlm.nih.gov/36598905/
7,Pokémon Go and augmented virtual reality games...,Maeve Serino,2016 Oct;28(5):673-7.,DOI: 10.1097/MOP.0000000000000409,Review,Purpose of review: The recent release of Pokém...,https://pubmed.ncbi.nlm.nih.gov/27479151/
8,Pokemon inhibits Bim transcription to promote ...,Yan Wang,2024 Aug 3;150(8):380.,DOI: 10.1007/s00432-024-05904-1,N/A,Purpose: This study aims to determine whether ...,https://pubmed.ncbi.nlm.nih.gov/39095579/
9,Pokémon GO and Physical Activity in Asia: Mult...,Ben D Ma,2018 Jun 15;20(6):e217.,DOI: 10.2196/jmir.9670,Review.,Background: Physical activity has long been co...,https://pubmed.ncbi.nlm.nih.gov/29907559/
10,Primary Care: Its Pokemon Moment,Bryan Becker,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...,https://pubmed.ncbi.nlm.nih.gov/38556037/
11,Impact of Pokémon Go on Physical Activity: A S...,Madina Khamzina,2020 Feb;58(2):270-282.,DOI: 10.1016/j.amepre.2019.09.005,Meta-Analysis,Context: Pokémon Go is a popular mobile augmen...,https://pubmed.ncbi.nlm.nih.gov/31836333/
12,Effects of Pokémon GO on Physical Activity and...,Jung Eun Lee,2021 Apr 25;10(9):1860.,DOI: 10.3390/jcm10091860,Review,"Augmented reality (AR) mobile game, Pokémon GO...",https://pubmed.ncbi.nlm.nih.gov/33922978/
13,Influence of Pokémon GO on Physical Activity a...,Haiyan Liang,2023 Nov 13:25:e49019.,DOI: 10.2196/49019,Review.,"Background: Pokémon GO, an augmented reality g...",https://pubmed.ncbi.nlm.nih.gov/37955949/
14,Going Forward with Pokemon Go,Yvette Chong,2018 Oct-Dec;11(4):243-246.,DOI: 10.4103/JETS.JETS_87_17,Review,Pokemon Go is an augmented reality (AR) game w...,https://pubmed.ncbi.nlm.nih.gov/30568365/
15,Pokemon contagion,B G Zifkin,2001 Dec;94(12):1235-6.,DOI: 10.1097/00007611-200112000-00025,Comment,NONE,https://pubmed.ncbi.nlm.nih.gov/11811868/
16,"Random forests, sound symbolism and Pokémon ev...",Alexander James Kilpatrick,2023 Jan 4;18(1):e0279350.,DOI: 10.1371/journal.pone.0279350,Review.,This study constructs machine learning algorit...,https://pubmed.ncbi.nlm.nih.gov/36598905/
17,Pokémon Go and augmented virtual reality games...,Maeve Serino,2016 Oct;28(5):673-7.,DOI: 10.1097/MOP.0000000000000409,Review,Purpose of review: The recent release of Pokém...,https://pubmed.ncbi.nlm.nih.gov/27479151/
18,Pokemon inhibits Bim transcription to promote ...,Yan Wang,2024 Aug 3;150(8):380.,DOI: 10.1007/s00432-024-05904-1,NONE,Purpose: This study aims to determine whether ...,https://pubmed.ncbi.nlm.nih.gov/39095579/
19,Pokémon GO and Physical Activity in Asia: Mult...,Ben D Ma,2018 Jun 15;20(6):e217.,DOI: 10.2196/jmir.9670,Review.,Background: Physical activity has long been co...,https://pubmed.ncbi.nlm.nih.gov/29907559/

#### 4) Exportar DataFrame para Excel

In [64]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [65]:
tabela.to_excel("pubmed_dados.xlsx", index=False)
print("\n✓ Arquivo 'pubmed_dados.xlsx' foi salvo com sucesso!")

✓ Arquivo 'pubmed_dados.xlsx' foi salvo com sucesso!