## Criando o Banco de Dados SQLite
### empresa.db

In [4]:
import sqlite3
import pandas as pd

In [5]:
conn = sqlite3.connect("empresa.db")
cursor = conn.cursor()

### 1 - Criando as tabelas

In [6]:
# Tabela 1: Funcionarios
cursor.execute("""
CREATE TABLE Funcionarios (
id INTEGER PRIMARY KEY,
nome TEXT,
cargo TEXT,
salario REAL,
data_contratacao TEXT not null
);
""")

OperationalError: table Funcionarios already exists

In [7]:
cursor.execute("Select * from Funcionarios")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

Empty DataFrame
Columns: [id, nome, cargo, salario, data_contratacao]
Index: []

### 2 - Inserindo os dados na tabela

In [26]:
# Inserindo em funcionarios
cursor.executemany(
    "INSERT INTO Funcionarios VALUES (?, ?, ?, ?, ?)",
    [
        (5, 'Luna', 'Gerente', 12000, '2026-07-01'),
        (6, 'Joana', 'DEV', 4000, '2026-09-01'),
        (7, 'Mauricio', 'Analista', 5000, '2026-03-07'),
        (8, 'Giovanna', 'DEV', 6000, '2026-04-06'),
    ]
)

conn.commit()

In [27]:
#vizualizndo
cursor.execute("Select * from Funcionarios")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id      nome     cargo  salario data_contratacao
0   1   Gustavo       DEV   4000.0       2026-01-01
1   3      João  Analista  10000.0       2026-03-01
2   4       Ana   Gerente   6000.0       2026-04-01
3   5      Luna   Gerente  12000.0       2026-07-01
4   6     Joana       DEV   4000.0       2026-09-01
5   7  Mauricio  Analista   5000.0       2026-03-07
6   8  Giovanna       DEV   6000.0       2026-04-06

#### VIZUALIZANDO PELO SALARIO

In [28]:
#Vizualizando dados por salario maior que 5000

cursor.execute("Select * from funcionarios where salario > 5000")
cursor.fetchall()

[(3, 'João', 'Analista', 10000.0, '2026-03-01'),
 (4, 'Ana', 'Gerente', 6000.0, '2026-04-01'),
 (5, 'Luna', 'Gerente', 12000.0, '2026-07-01'),
 (8, 'Giovanna', 'DEV', 6000.0, '2026-04-06')]

#### VIZUALIZANDO PELO CARGO

In [29]:
#Vizualizando dados por cargo igual a gerente

cursor.execute("Select * from funcionarios where cargo = 'Gerente'")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id  nome    cargo  salario data_contratacao
0   4   Ana  Gerente   6000.0       2026-04-01
1   5  Luna  Gerente  12000.0       2026-07-01

#### ATUALIZANDO DADOS

In [17]:
# Dando aumento para um funcionario

cursor.execute("UPDATE funcionarios set salario = 10000 where id = 3")
conn.commit()
print("Registro atualizado com sucesso!")

[]

In [18]:
cursor.execute("Select * from funcionarios where id = 3")
cursor.fetchall()

[(3, 'João', 'Analista', 10000.0, '2026-03-01')]

#### EXCLUSÃO

In [19]:
cursor.execute("DELETE FROM funcionarios where id = 2")
conn.commit()
print("Registro deletado com sucesso!")

Registro deletado com sucesso!

In [31]:
cursor.execute("Select * from funcionarios")
cursor.fetchall()

[(1, 'Gustavo', 'DEV', 4000.0, '2026-01-01'),
 (3, 'João', 'Analista', 10000.0, '2026-03-01'),
 (4, 'Ana', 'Gerente', 6000.0, '2026-04-01'),
 (5, 'Luna', 'Gerente', 12000.0, '2026-07-01'),
 (6, 'Joana', 'DEV', 4000.0, '2026-09-01'),
 (7, 'Mauricio', 'Analista', 5000.0, '2026-03-07'),
 (8, 'Giovanna', 'DEV', 6000.0, '2026-04-06')]

### 3 - Agregação e Ordenação

#### SOMA TOTAL DOS SALARIOS

In [32]:
cursor.execute("Select SUM(salario) from funcionarios")
cursor.fetchone()[0]

47000.0

#### MEDIA SALARIAL

In [33]:
cursor.execute("Select AVG(salario) from funcionarios")
cursor.fetchone()[0]

6714.285714285715

#### MAIOR X MENOR

In [34]:
cursor.execute("Select MAX(salario), MIN(salario) from funcionarios")
cursor.fetchone()

(12000.0, 4000.0)

#### AGRUPAMENTOS

* CALCULO MEDIO DO SALARIO POR CARGO

In [42]:
cursor.execute("""
    SELECT cargo, AVG(salario) AS media
    FROM funcionarios
    GROUP BY cargo
""")

pd.DataFrame(cursor.fetchall(), columns=['cargo', 'media'])

      cargo        media
0  Analista  7500.000000
1       DEV  4666.666667
2   Gerente  9000.000000

* Quantidade de funcionarios por cargo

In [43]:
cursor.execute("Select cargo, COUNT(*) as quantidade from funcionarios group by cargo")

pd.DataFrame(cursor.fetchall(), columns=['cargo', 'quantidade'])

      cargo  quantidade
0  Analista           2
1       DEV           3
2   Gerente           2

#### ORDENAÇÃO

* Selecionar o todos os funcionario e ordenar do maior para o menor salario

In [45]:
cursor.execute("Select * from funcionarios order by salario desc")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id      nome     cargo  salario data_contratacao
0   5      Luna   Gerente  12000.0       2026-07-01
1   3      João  Analista  10000.0       2026-03-01
2   4       Ana   Gerente   6000.0       2026-04-01
3   8  Giovanna       DEV   6000.0       2026-04-06
4   7  Mauricio  Analista   5000.0       2026-03-07
5   1   Gustavo       DEV   4000.0       2026-01-01
6   6     Joana       DEV   4000.0       2026-09-01

* Selecionar funcionarios em ordem alfabetica

In [46]:
cursor.execute("Select * from funcionarios order by nome asc")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id      nome     cargo  salario data_contratacao
0   4       Ana   Gerente   6000.0       2026-04-01
1   8  Giovanna       DEV   6000.0       2026-04-06
2   1   Gustavo       DEV   4000.0       2026-01-01
3   6     Joana       DEV   4000.0       2026-09-01
4   3      João  Analista  10000.0       2026-03-01
5   5      Luna   Gerente  12000.0       2026-07-01
6   7  Mauricio  Analista   5000.0       2026-03-07

### 4 - TRANSAÇÕES ROLLBACK

In [47]:
# SIMULAÇÃO Transação 

try:
    conn.execute("BEGIN TRANSACTION") # Inicia a transação
    cursor.execute("INSERT INTO funcionarios VALUES (9, 'Carlos', 'Analista', 7000, '2026-05-01')") # inserindo 
    raise Exception("Erro simulado") # Simula um erro
    conn.commit() # Se tudo estiver certo, confirma a transação
except:
    conn.rollback() # Reverte em caso de erro
    print("Transação revertida por erro")

Transação revertida por erro

In [49]:
# Transação verdadeira
try:
    conn.execute("BEGIN TRANSACTION") # Inicia a transação
    cursor.execute("INSERT INTO funcionarios VALUES (10, 'Eduardo', 'Chefe', 70000, '2026-09-29')") # inserindo 
    conn.commit() # Se tudo estiver certo, confirma a transação
except:
    conn.rollback() # Reverte em caso de erro
    print("Transação revertida por erro")

In [50]:
cursor.execute("Select * from funcionarios order by salario desc")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id      nome     cargo  salario data_contratacao
0  10   Eduardo     Chefe  70000.0       2026-09-29
1   5      Luna   Gerente  12000.0       2026-07-01
2   3      João  Analista  10000.0       2026-03-01
3   4       Ana   Gerente   6000.0       2026-04-01
4   8  Giovanna       DEV   6000.0       2026-04-06
5   7  Mauricio  Analista   5000.0       2026-03-07
6   1   Gustavo       DEV   4000.0       2026-01-01
7   6     Joana       DEV   4000.0       2026-09-01

### JOINS

* Criando uma segunda tabela

In [52]:
# Tabela 2: Departamentos
cursor.execute("""
CREATE TABLE Departamentos (
id INTEGER PRIMARY KEY,
nome TEXT not null,
localizacao TEXT
);
""")

* Inserindo na tabela departamento

In [53]:
cursor.executemany(
    "INSERT INTO Departamentos VALUES (?, ?, ?)",
    [
        (1, 'Financeiro', 'São Paulo'),
        (2, 'TI', 'São Paulo'),
        (3, 'Recursos Humanos', 'Itapevi'),
        (4, 'Marketing', 'Jandira'),
    ]
)

conn.commit()

### CHAVE ESTRANGEIRA E JOINS

In [59]:
# Adicionando a chave estrangeira em funcionarios
try:
    conn.execute("PRAGMA foreign_keys = ON")
    cursor.execute("ALTER TABLE funcionarios ADD COLUMN departamento_id INTEGER REFERENCES departamentos(id)")
except sqlite3.OperationalError:
    pass

# Relacionando cada funcionario a um departamento
cursor.executemany(
    "UPDATE funcionarios SET departamento_id = ? WHERE id = ?",
    [
        (2, 1),
        (3, 3),
        (1, 4),
        (1, 5),
        (2, 6),
        (2, 7),
        (3, 8),
        (4, 10),
    ]
)

conn.commit()

#### INNER JOIN

* Funcionarios e seus departamentos

In [61]:
cursor.execute("""
    SELECT funcionarios.nome AS funcionario,
           departamentos.nome AS departamento
    FROM funcionarios
    INNER JOIN departamentos
        ON funcionarios.departamento_id = departamentos.id
""")

pd.DataFrame(cursor.fetchall(), columns=['funcionario', 'departamento'])

  funcionario      departamento
0     Gustavo                TI
1        João  Recursos Humanos
2         Ana        Financeiro
3        Luna        Financeiro
4       Joana                TI
5    Mauricio                TI
6    Giovanna  Recursos Humanos
7     Eduardo         Marketing

#### LEFT JOIN

* Criando as tabelas de projetos e da relação entre funcionarios e projetos

In [56]:
cursor.execute("""
    CREATE TABLE projetos (
        id INTEGER PRIMARY KEY,
        nome_projeto TEXT NOT NULL
    )
""")

cursor.execute("""
    CREATE TABLE funcionarios_projetos (
        funcionario_id INTEGER,
        projeto_id INTEGER,
        PRIMARY KEY (funcionario_id, projeto_id),
        FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id),
        FOREIGN KEY (projeto_id) REFERENCES projetos(id)
    )
""")

cursor.executemany(
    "INSERT INTO projetos VALUES (?, ?)",
    [
        (1, 'Sistema Financeiro'),
        (2, 'Aplicativo da Empresa'),
        (3, 'Dashboard de Indicadores'),
    ]
)

cursor.executemany(
    "INSERT INTO funcionarios_projetos VALUES (?, ?)",
    [
        (5, 1),
        (6, 2),
        (7, 2),
        (7, 3),
        (8, 3),
    ]
)

conn.commit()

In [60]:
cursor.execute("""
    SELECT funcionarios.nome AS funcionario,
           projetos.nome_projeto AS projeto
    FROM funcionarios
    LEFT JOIN funcionarios_projetos
        ON funcionarios.id = funcionarios_projetos.funcionario_id
    LEFT JOIN projetos
        ON funcionarios_projetos.projeto_id = projetos.id
    ORDER BY funcionarios.nome
""")

pd.DataFrame(cursor.fetchall(), columns=['funcionario', 'projeto'])

  funcionario                   projeto
0         Ana                       NaN
1     Eduardo                       NaN
2    Giovanna  Dashboard de Indicadores
3     Gustavo                       NaN
4       Joana     Aplicativo da Empresa
5        João                       NaN
6        Luna        Sistema Financeiro
7    Mauricio     Aplicativo da Empresa
8    Mauricio  Dashboard de Indicadores

### 6 - DCL (Controle de Dados)

- **DDL (Data Definition Language):** usado para definir e modificar a estrutura do banco de dados, como tabelas, colunas e restrições. Exemplos: `CREATE`, `ALTER` e `DROP`.
- **DML (Data Manipulation Language):** usado para inserir, alterar e excluir registros nas tabelas. Exemplos: `INSERT`, `UPDATE` e `DELETE`.
- **DQL (Data Query Language):** usado para consultar e recuperar dados armazenados. O principal comando é o `SELECT`.
- **DCL (Data Control Language):** usado para controlar o acesso e as permissões dos usuários sobre o banco de dados. Exemplos: `GRANT`, que concede permissões, e `REVOKE`, que remove permissões.

O DCL é importante para proteger os dados, permitindo que cada usuário tenha somente os acessos necessários para realizar suas funções.

In [62]:
# Encerrando a conexão com o banco de dados após concluir os exercícios
conn.close()
print("Conexão com o banco de dados encerrada com sucesso!")

Conexão com o banco de dados encerrada com sucesso!