## Criando o Banco de Dados SQLite
### empresa.db

In [4]:
import sqlite3
import pandas as pd

In [5]:
conn = sqlite3.connect("empresa.db")
cursor = conn.cursor()

### 1 - Criando as tabelas

In [6]:
# Tabela 1: Funcionarios
cursor.execute("""
CREATE TABLE Funcionarios (
id INTEGER PRIMARY KEY,
nome TEXT,
cargo TEXT,
salario REAL,
data_contratacao TEXT not null
);
""")

OperationalError: table Funcionarios already exists

In [7]:
cursor.execute("Select * from Funcionarios")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

Empty DataFrame
Columns: [id, nome, cargo, salario, data_contratacao]
Index: []

### 2 - Inserindo os dados na tabela

In [26]:
# Inserindo em funcionarios
cursor.executemany(
    "INSERT INTO Funcionarios VALUES (?, ?, ?, ?, ?)",
    [
        (5, 'Luna', 'Gerente', 12000, '2026-07-01'),
        (6, 'Joana', 'DEV', 4000, '2026-09-01'),
        (7, 'Mauricio', 'Analista', 5000, '2026-03-07'),
        (8, 'Giovanna', 'DEV', 6000, '2026-04-06'),
    ]
)

conn.commit()

In [27]:
#vizualizndo
cursor.execute("Select * from Funcionarios")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id      nome     cargo  salario data_contratacao
0   1   Gustavo       DEV   4000.0       2026-01-01
1   3      João  Analista  10000.0       2026-03-01
2   4       Ana   Gerente   6000.0       2026-04-01
3   5      Luna   Gerente  12000.0       2026-07-01
4   6     Joana       DEV   4000.0       2026-09-01
5   7  Mauricio  Analista   5000.0       2026-03-07
6   8  Giovanna       DEV   6000.0       2026-04-06

#### VIZUALIZANDO PELO SALARIO

In [28]:
#Vizualizando dados por salario maior que 5000

cursor.execute("Select * from funcionarios where salario > 5000")
cursor.fetchall()

[(3, 'João', 'Analista', 10000.0, '2026-03-01'),
 (4, 'Ana', 'Gerente', 6000.0, '2026-04-01'),
 (5, 'Luna', 'Gerente', 12000.0, '2026-07-01'),
 (8, 'Giovanna', 'DEV', 6000.0, '2026-04-06')]

#### VIZUALIZANDO PELO CARGO

In [29]:
#Vizualizando dados por cargo igual a gerente

cursor.execute("Select * from funcionarios where cargo = 'Gerente'")
pd.DataFrame(cursor.fetchall(), columns = ['id','nome','cargo','salario','data_contratacao'])

   id  nome    cargo  salario data_contratacao
0   4   Ana  Gerente   6000.0       2026-04-01
1   5  Luna  Gerente  12000.0       2026-07-01

#### ATUALIZANDO DADOS

In [ ]:
# Dando aumento para um funcionario

cursor.execute("UPDATE funcionarios set salario = 10000 where id = 3")
conn.commit()
print("Registro atualizado com sucesso!")

[]

In [18]:
cursor.execute("Select * from funcionarios where id = 3")
cursor.fetchall()

[(3, 'João', 'Analista', 10000.0, '2026-03-01')]

#### EXCLUSÃO

In [19]:
cursor.execute("DELETE FROM funcionarios where id = 2")
conn.commit()
print("Registro deletado com sucesso!")

Registro deletado com sucesso!

In [31]:
cursor.execute("Select * from funcionarios")
cursor.fetchall()

[(1, 'Gustavo', 'DEV', 4000.0, '2026-01-01'),
 (3, 'João', 'Analista', 10000.0, '2026-03-01'),
 (4, 'Ana', 'Gerente', 6000.0, '2026-04-01'),
 (5, 'Luna', 'Gerente', 12000.0, '2026-07-01'),
 (6, 'Joana', 'DEV', 4000.0, '2026-09-01'),
 (7, 'Mauricio', 'Analista', 5000.0, '2026-03-07'),
 (8, 'Giovanna', 'DEV', 6000.0, '2026-04-06')]

### 3 - Agregação e Ordenação

#### SOMA TOTAL DOS SALARIOS

In [32]:
cursor.execute("Select SUM(salario) from funcionarios")
cursor.fetchone()[0]

47000.0

#### MEDIA SALARIAL

In [33]:
cursor.execute("Select AVG(salario) from funcionarios")
cursor.fetchone()[0]

6714.285714285715

#### MAIOR X MENOR

In [34]:
cursor.execute("Select MAX(salario), MIN(salario) from funcionarios")
cursor.fetchone()

(12000.0, 4000.0)

#### AGRUPAMENTOS

* CALCULO MEDIO DO SALARIO POR CARGO